### ISSUE TITLE
Fix dependency vulnerability alerts

### ISSUE THREAD

**Issue by mrwest808** [viablelab/bracket-padder-vscode#1]
The `vscode` package implicitly depends on the compromised `event-stream` library, dominictarr/event-stream#116.

This has been reported in Microsoft/vscode-extension-vscode#126.

**Comment by kondratyev-nv** [comment]
JFYI as a quick fix you can run `npm install --dev event-stream@3.3.4` to pin this versioin in package-lock.json.

**Comment by mrwest808** [comment]
@kondratyev-nv Thanks, I'll do that until the `vscode` package is updated.

**Comment by mrwest808** [comment]
Updated `vscode` to version 1.1.22 in 2e9aa22.
