### ISSUE TITLE
Deleting space 

### ISSUE THREAD

**Issue by pksunkara** [viablelab/bracket-padder-vscode#5]
Assuming we have, `{.|.}`, if I press backspace, currently it does, `{|.}`. Can we have `{|}`?

**Comment by mrwest808** [comment]
Absolutely, it's supposed to work like that, I'm not sure when it stopped working. I'll take a look at this within the next few days.

**Comment by mrwest808** [comment]
I get the expected behavior in my development environment. Will need to investigate this in more detail and perhaps do some rewrites.

**Comment by pksunkara** [comment]
Can confirm it is not working without development environment. The other 2 actions are working.

**Comment by pksunkara** [comment]
Hey, any update on this?

**Comment by mrwest808** [comment]
Afraid not, got a bit discouraged when I couldn’t replicate the bug in development mode, and the lack of this functionality hasn’t really bothered me in my day to day work.

I might take a look at this in the near future, but can’t guarantee when.

Feel free to take a stab at it if you want.

**Comment by MehbubRashid** [comment]
Same issue..it produces the space nicely..but when deleting, it does not delete the space..so the extension is giving benefit and also giving an issue together.
![vscode](https://user-images.githubusercontent.com/34944930/99151937-d2fc5900-26c8-11eb-9c00-ce73acd0cd01.gif)

**Comment by mrwest808** [comment]
I took a quick look at Microsoft's extension-samples repository, and it seems like there may be other API options for implementing this than what was available ~3 years ago, so I think a partial rewrite may be beneficial.

I'll take a closer look when I have some spare time.

**Comment by mrwest808** [comment]
Released in [v0.3.0](https://github.com/viablelab/bracket-padder-vscode/releases/tag/v0.3.0)
